# Generated by Django 5.2.17 on 2026-09-29 08:13

import django.db.models.deletion
import modelsearch.index
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="1–2 речення під заголовком: для кого сторінка і що тут можна дізнатися.",
                        max_length=400,
                        verbose_name="Вступ",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("leadership", "Керівництво"),
                            ("departments", "Структура (відділи)"),
                            ("specialists", "Фахівці із супроводу ветеранів"),
                            ("spaces", "Ветеранські простори"),
                        ],
                        help_text="Записи редагуються в розділі «Фрагменти» адмінки; сторінка оновлюється сама.",
                        max_length=20,
                        verbose_name="Що показувати",
                    ),
                ),
            ],
            options={
                "verbose_name": "Довідник (керівництво, відділи, фахівці, простори)",
                "verbose_name_plural": "Довідники",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Менше число — вище у списку.",
                        verbose_name="Порядок у списку",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Назва відділу"),
                ),
                (
                    "functions",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Коротко: чим займається відділ і з якими питаннями до нього звертатися.",
                        verbose_name="Основні функції",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Порожньо — адреса управління з налаштувань.",
                        max_length=250,
                        verbose_name="Адреса",
                    ),
                ),
                (
                    "room",
                    models.CharField(blank=True, max_length=50, verbose_name="Кабінет"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Як показувати відвідувачам: (05361) 7-00-00",
                        max_length=30,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Електронна пошта"
                    ),
                ),
                (
                    "hours",
                    models.CharField(
                        blank=True,
                        help_text="Напр. «Пн–Чт 08:00–17:15»",
                        max_length=200,
                        verbose_name="Години прийому",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Відділ",
                "verbose_name_plural": "Відділи",
                "ordering": ["sort_order", "pk"],
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Менше число — вище у списку.",
                        verbose_name="Порядок у списку",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Прізвище, ім'я, по батькові"
                    ),
                ),
                ("position", models.CharField(max_length=200, verbose_name="Посада")),
                (
                    "is_leadership",
                    models.BooleanField(
                        default=False,
                        help_text="Показувати на сторінці «Керівництво» і в контактах.",
                        verbose_name="Керівництво",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Як показувати відвідувачам: (05361) 7-00-00",
                        max_length=30,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Електронна пошта"
                    ),
                ),
                (
                    "reception",
                    models.CharField(
                        blank=True,
                        help_text="Дні й години особистого прийому громадян, напр. «Вівторок, 09:00–12:00».",
                        max_length=200,
                        verbose_name="Особистий прийом",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="people",
                        to="organization.department",
                        verbose_name="Відділ",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Лише за письмовою згодою працівника на оприлюднення фото. Альтернативний текст підставляється автоматично: ім'я працівника.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Працівник",
                "verbose_name_plural": "Працівники",
                "ordering": ["sort_order", "pk"],
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="VeteranSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Менше число — вище у списку.",
                        verbose_name="Порядок у списку",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Назва")),
                ("address", models.CharField(max_length=250, verbose_name="Адреса")),
                (
                    "hours",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Години роботи"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Як показувати відвідувачам: (05361) 7-00-00",
                        max_length=30,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "services",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Що тут можна отримати.",
                        verbose_name="Послуги",
                    ),
                ),
                (
                    "map_url",
                    models.URLField(
                        blank=True, verbose_name="Посилання на Google Maps"
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Фото простору. Альтернативний текст береться з опису зображення в бібліотеці.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ветеранський простір",
                "verbose_name_plural": "Ветеранські простори",
                "ordering": ["sort_order", "pk"],
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="VeteranSpecialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Менше число — вище у списку.",
                        verbose_name="Порядок у списку",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Прізвище, ім'я, по батькові"
                    ),
                ),
                (
                    "territory",
                    models.CharField(
                        help_text="Старостинський округ, мікрорайон або «усі громади».",
                        max_length=200,
                        verbose_name="Територія обслуговування",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Як показувати відвідувачам: (05361) 7-00-00",
                        max_length=30,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Електронна пошта"
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Графік прийому"
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фахівець із супроводу ветеранів",
                "verbose_name_plural": "Фахівці із супроводу ветеранів",
                "ordering": ["sort_order", "pk"],
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
