# Generated by Django 5.2.17 on 2026-09-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Заповнюйте, лише якщо відділ працює не за адресою управління.",
                max_length=250,
                verbose_name="Адреса",
            ),
        ),
    ]
