# Generated by Django 5.2.17 on 2026-09-29 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_department_address_help"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veteranspace",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                help_text="Фото простору. Альтернативний текст — «Опис» зображення в бібліотеці (обов'язковий).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Фото",
            ),
        ),
    ]
