# Generated by Django 5.2.17 on 2026-09-29 08:13

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import uuid
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="1–2 речення під заголовком: для кого сторінка і що тут можна дізнатися.",
                        max_length=400,
                        verbose_name="Вступ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список оголошень",
                "verbose_name_plural": "Списки оголошень",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AnnouncementPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="1–2 речення під заголовком: для кого сторінка і що тут можна дізнатися.",
                        max_length=400,
                        verbose_name="Вступ",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата публікації",
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Для оголошень про прийом, збори тощо. Порожньо, якщо події немає.",
                        null=True,
                        verbose_name="Дата й час події",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Після цієї дати оголошення автоматично переходить в архів. Порожньо — оголошення актуальне без обмеження строку.",
                        null=True,
                        verbose_name="Діє до",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 3),
                            ("image", 6),
                            ("documents", 10),
                            ("accordion", 16),
                            ("table", 22),
                            ("callout", 26),
                            ("contact_card", 33),
                            ("button", 38),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Текст заголовка", "max_length": 120},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Заголовок розділу (H2)"),
                                        ("h3", "Підзаголовок (H3)"),
                                    ],
                                    "help_text": "H3 використовуйте лише всередині розділу з H2, щоб не порушувати структуру.",
                                    "label": "Рівень",
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("apps.core.blocks.ParagraphBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {
                                    "help_text": "Альтернативний текст обов'язковий: опишіть, що зображено і навіщо це на сторінці. Позначте як декоративне, лише якщо зображення не несе змісту.",
                                    "label": "Зображення",
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Підпис",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Показується як заголовок (H2 або H3 залежно від місця на сторінці).",
                                    "label": "Заголовок списку",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Документ"},
                            ),
                            9: (
                                "wagtail.blocks.ListBlock",
                                (8,),
                                {"label": "Документи", "min_num": 1},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 7), ("documents", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Наприклад, «Часті питання».",
                                    "label": "Заголовок блоку",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Питання", "max_length": 250},
                            ),
                            13: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                    ],
                                    "label": "Відповідь",
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 12), ("answer", 13)]],
                                {"label": "Питання"},
                            ),
                            15: (
                                "wagtail.blocks.ListBlock",
                                (14,),
                                {"label": "Питання й відповіді", "min_num": 1},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 11), ("items", 15)]],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Обов'язково: назва допомагає користувачам скрінрідерів зрозуміти таблицю.",
                                    "label": "Назва таблиці",
                                    "max_length": 200,
                                },
                            ),
                            18: ("wagtail.blocks.CharBlock", (), {"label": "Текст"}),
                            19: ("wagtail.blocks.DecimalBlock", (), {"label": "Число"}),
                            20: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "link"],
                                    "label": "Текст із посиланнями",
                                },
                            ),
                            21: (
                                "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                                [[("text", 18), ("number", 19), ("rich_text", 20)]],
                                {"label": "Таблиця"},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("caption", 17), ("table", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Інформація"),
                                        ("success", "Успіх / підтвердження"),
                                        ("warning", "Увага"),
                                        ("danger", "Важливе попередження"),
                                    ],
                                    "label": "Тип",
                                },
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Заголовок",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            25: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [[("variant", 23), ("title", 24), ("text", 25)]],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Назва (відділ, посада)", "max_length": 150},
                            ),
                            28: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Адреса",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Кабінет",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            30: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Як показувати, напр. (05361) 7-00-00",
                                    "label": "Телефон",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            31: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {"label": "Електронна пошта", "required": False},
                            ),
                            32: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Години прийому",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            33: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 27),
                                        ("address", 28),
                                        ("room", 29),
                                        ("phone", 30),
                                        ("email", 31),
                                        ("hours", 32),
                                    ]
                                ],
                                {},
                            ),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Має бути зрозумілим без контексту: «Завантажити бланк заяви», а не «Тут».",
                                    "label": "Текст кнопки",
                                    "max_length": 60,
                                },
                            ),
                            35: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Сторінка сайту", "required": False},
                            ),
                            36: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Або зовнішнє посилання", "required": False},
                            ),
                            37: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Основна кнопка"),
                                        ("secondary", "Другорядна кнопка"),
                                    ],
                                    "label": "Вигляд",
                                },
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 34),
                                        ("page", 35),
                                        ("url", 36),
                                        ("style", 37),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Текст оголошення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оголошення",
                "verbose_name_plural": "Оголошення",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="1–2 речення під заголовком: для кого сторінка і що тут можна дізнатися.",
                        max_length=400,
                        verbose_name="Вступ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список новин",
                "verbose_name_plural": "Списки новин",
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="NewsTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Назва")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="Латиницею або кирилицею без пробілів, напр. «veteranam».",
                        max_length=80,
                        verbose_name="Ідентифікатор в адресі",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема новин",
                "verbose_name_plural": "Теми новин",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NewsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="1–2 речення під заголовком: для кого сторінка і що тут можна дізнатися.",
                        max_length=400,
                        verbose_name="Вступ",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Дата"
                    ),
                ),
                (
                    "cover_caption",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Підпис до фото"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 3),
                            ("image", 6),
                            ("documents", 10),
                            ("accordion", 16),
                            ("table", 22),
                            ("callout", 26),
                            ("contact_card", 33),
                            ("button", 38),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Текст заголовка", "max_length": 120},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Заголовок розділу (H2)"),
                                        ("h3", "Підзаголовок (H3)"),
                                    ],
                                    "help_text": "H3 використовуйте лише всередині розділу з H2, щоб не порушувати структуру.",
                                    "label": "Рівень",
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("apps.core.blocks.ParagraphBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {
                                    "help_text": "Альтернативний текст обов'язковий: опишіть, що зображено і навіщо це на сторінці. Позначте як декоративне, лише якщо зображення не несе змісту.",
                                    "label": "Зображення",
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Підпис",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Показується як заголовок (H2 або H3 залежно від місця на сторінці).",
                                    "label": "Заголовок списку",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Документ"},
                            ),
                            9: (
                                "wagtail.blocks.ListBlock",
                                (8,),
                                {"label": "Документи", "min_num": 1},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 7), ("documents", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Наприклад, «Часті питання».",
                                    "label": "Заголовок блоку",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Питання", "max_length": 250},
                            ),
                            13: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                    ],
                                    "label": "Відповідь",
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 12), ("answer", 13)]],
                                {"label": "Питання"},
                            ),
                            15: (
                                "wagtail.blocks.ListBlock",
                                (14,),
                                {"label": "Питання й відповіді", "min_num": 1},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 11), ("items", 15)]],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Обов'язково: назва допомагає користувачам скрінрідерів зрозуміти таблицю.",
                                    "label": "Назва таблиці",
                                    "max_length": 200,
                                },
                            ),
                            18: ("wagtail.blocks.CharBlock", (), {"label": "Текст"}),
                            19: ("wagtail.blocks.DecimalBlock", (), {"label": "Число"}),
                            20: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "link"],
                                    "label": "Текст із посиланнями",
                                },
                            ),
                            21: (
                                "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                                [[("text", 18), ("number", 19), ("rich_text", 20)]],
                                {"label": "Таблиця"},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("caption", 17), ("table", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Інформація"),
                                        ("success", "Успіх / підтвердження"),
                                        ("warning", "Увага"),
                                        ("danger", "Важливе попередження"),
                                    ],
                                    "label": "Тип",
                                },
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Заголовок",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            25: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [[("variant", 23), ("title", 24), ("text", 25)]],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Назва (відділ, посада)", "max_length": 150},
                            ),
                            28: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Адреса",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Кабінет",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            30: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Як показувати, напр. (05361) 7-00-00",
                                    "label": "Телефон",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            31: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {"label": "Електронна пошта", "required": False},
                            ),
                            32: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Години прийому",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            33: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 27),
                                        ("address", 28),
                                        ("room", 29),
                                        ("phone", 30),
                                        ("email", 31),
                                        ("hours", 32),
                                    ]
                                ],
                                {},
                            ),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Має бути зрозумілим без контексту: «Завантажити бланк заяви», а не «Тут».",
                                    "label": "Текст кнопки",
                                    "max_length": 60,
                                },
                            ),
                            35: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Сторінка сайту", "required": False},
                            ),
                            36: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Або зовнішнє посилання", "required": False},
                            ),
                            37: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Основна кнопка"),
                                        ("secondary", "Другорядна кнопка"),
                                    ],
                                    "label": "Вигляд",
                                },
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 34),
                                        ("page", 35),
                                        ("url", 36),
                                        ("style", 37),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Текст новини",
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        help_text="Горизонтальне фото 16:9. Альтернативний текст — опис зображення в бібліотеці: що на фото, а не «фото».",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Обкладинка",
                    ),
                ),
                (
                    "topics",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="news.newstopic", verbose_name="Теми"
                    ),
                ),
            ],
            options={
                "verbose_name": "Новина",
                "verbose_name_plural": "Новини",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddConstraint(
            model_name="newstopic",
            constraint=models.UniqueConstraint(
                fields=("slug", "locale"), name="unique_topic_slug_per_locale"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="newstopic",
            unique_together={("translation_key", "locale")},
        ),
    ]
