# Generated by Django 5.2.17 on 2026-09-29 07:06

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("main", "Головне меню (шапка)"),
                            ("footer", "Меню футера (службові сторінки)"),
                        ],
                        max_length=20,
                        verbose_name="Розташування",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "url",
                    models.URLField(blank=True, verbose_name="Або зовнішнє посилання"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Необов'язково для сторінки: типово береться назва сторінки.",
                        max_length=60,
                        verbose_name="Назва пункту",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Одне речення про розділ, показується у спливному меню на комп'ютері.",
                        max_length=150,
                        verbose_name="Опис у мегаменю",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Сторінка",
                    ),
                ),
                (
                    "menu",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.navigationmenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункти меню",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Повна адреса з індексом, напр. «вул. …, 1, м. Лубни, Полтавська обл., 37500».",
                        max_length=250,
                        verbose_name="Адреса",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Електронна пошта"
                    ),
                ),
                (
                    "phones",
                    wagtail.fields.StreamField(
                        [("phone", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Напр. «Приймальня»",
                                    "label": "Підпис",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Як показувати: (05361) 7-00-00",
                                    "label": "Номер",
                                    "max_length": 30,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("number", 1)]],
                                {},
                            ),
                        },
                        verbose_name="Телефони",
                    ),
                ),
                (
                    "schedule",
                    wagtail.fields.StreamField(
                        [("row", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Напр. «Понеділок – четвер»",
                                    "label": "Дні",
                                    "max_length": 60,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Напр. «08:00 – 17:15»",
                                    "label": "Години",
                                    "max_length": 60,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("days", 0), ("hours", 1)]],
                                {},
                            ),
                        },
                        help_text="Кожен рядок — дні та години, включно з обідньою перервою й вихідними.",
                        verbose_name="Графік роботи",
                    ),
                ),
                (
                    "map_url",
                    models.URLField(
                        blank=True,
                        help_text="Лише посилання, без вбудованої карти.",
                        verbose_name="Посилання на Google Maps",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Сторінка у Facebook"),
                ),
                (
                    "council_url",
                    models.URLField(
                        blank=True, verbose_name="Сайт Лубенської міської ради"
                    ),
                ),
                (
                    "content_license",
                    models.CharField(
                        blank=True,
                        help_text="Рядок у футері, напр. «Матеріали сайту доступні за ліцензією CC BY 4.0, якщо не зазначено інше». Порожньо — рядок не показується.",
                        max_length=250,
                        verbose_name="Ліцензія на матеріали сайту",
                    ),
                ),
                (
                    "alert_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Показувати термінове оголошення"
                    ),
                ),
                (
                    "alert_text",
                    models.CharField(
                        blank=True,
                        help_text="Одне коротке речення. Показується жовтим банером над шапкою на всіх сторінках.",
                        max_length=200,
                        verbose_name="Текст оголошення",
                    ),
                ),
                (
                    "alert_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Сторінка з деталями",
                    ),
                ),
                (
                    "emblem",
                    models.ForeignKey(
                        blank=True,
                        help_text="SVG або PNG із прозорим фоном. Поки не задано, показується тимчасова заглушка.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Герб",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Налаштування сайту",
            },
        ),
        migrations.AddConstraint(
            model_name="navigationmenu",
            constraint=models.UniqueConstraint(
                fields=("location", "locale"), name="unique_menu_per_locale"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="navigationmenu",
            unique_together={("translation_key", "locale")},
        ),
    ]
