# Generated by Django 5.2.17 on 2026-09-29 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="emblem",
            field=models.ForeignKey(
                blank=True,
                help_text="PNG або WebP із прозорим фоном, висотою від 96 px. Поки не задано, показується тимчасова заглушка.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Герб",
            ),
        ),
    ]
