# Generated by Django 5.2.17 on 2026-09-29 07:06

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="featured_pages",
            field=wagtail.fields.StreamField(
                [("page", 0)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.PageChooserBlock", (), {"label": "Сторінка"})
                },
                help_text="До 6 сторінок. На картці показується назва й опис сторінки.",
                verbose_name="Ключові послуги та програми",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_heading",
            field=models.CharField(
                default="Управління соціальної та ветеранської політики Лубенської міської ради",
                max_length=150,
                verbose_name="Заголовок на головній",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_text",
            field=models.TextField(
                blank=True,
                help_text="1–2 речення: чим управління допомагає мешканцям громади.",
                max_length=300,
                verbose_name="Текст під заголовком",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="tiles",
            field=wagtail.fields.StreamField(
                [("tile", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Назва", "max_length": 60},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Короткий опис", "max_length": 80, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("shield", "Щит (ветерани)"),
                                ("home", "Дім (житло, ВПО)"),
                                ("heart", "Серце (соціальні послуги)"),
                                ("percent", "Відсоток (пільги)"),
                                ("activity", "Пульс (реабілітація)"),
                                ("clock", "Годинник (графік)"),
                                ("phone", "Телефон (контакти)"),
                                ("landmark", "Будівля (публічна інформація)"),
                                ("users", "Люди"),
                                ("file-text", "Документ"),
                                ("calendar", "Календар"),
                                ("megaphone", "Гучномовець (оголошення)"),
                                ("newspaper", "Газета (новини)"),
                                ("info", "Інформація"),
                            ],
                            "label": "Іконка",
                        },
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Сторінка сайту", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Або зовнішнє посилання", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Оливковий колір іконки.",
                            "label": "Ветеранський акцент",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("text", 1),
                                ("icon", 2),
                                ("page", 3),
                                ("url", 4),
                                ("veteran", 5),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="6–8 плиток за життєвими ситуаціями: «Ветеранам», «ВПО», «Пільги» тощо.",
                verbose_name="Плитки «Що вам потрібно?»",
            ),
        ),
    ]
