# Generated by Django 5.2.17 on 2026-09-29 07:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="1–2 речення під заголовком: для кого сторінка і що тут можна дізнатися.",
                        max_length=400,
                        verbose_name="Вступ",
                    ),
                ),
                (
                    "accent",
                    models.CharField(
                        choices=[
                            ("default", "Основний (синій)"),
                            ("veteran", "Ветеранський (оливковий)"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="Колірний акцент",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 3),
                            ("image", 6),
                            ("documents", 10),
                            ("accordion", 16),
                            ("table", 22),
                            ("callout", 26),
                            ("contact_card", 33),
                            ("button", 38),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Текст заголовка", "max_length": 120},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Заголовок розділу (H2)"),
                                        ("h3", "Підзаголовок (H3)"),
                                    ],
                                    "help_text": "H3 використовуйте лише всередині розділу з H2, щоб не порушувати структуру.",
                                    "label": "Рівень",
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("apps.core.blocks.ParagraphBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {
                                    "help_text": "Альтернативний текст обов'язковий: опишіть, що зображено і навіщо це на сторінці. Позначте як декоративне, лише якщо зображення не несе змісту.",
                                    "label": "Зображення",
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Підпис",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Заголовок списку",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Документ"},
                            ),
                            9: (
                                "wagtail.blocks.ListBlock",
                                (8,),
                                {"label": "Документи", "min_num": 1},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 7), ("documents", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Наприклад, «Часті питання».",
                                    "label": "Заголовок блоку",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Питання", "max_length": 250},
                            ),
                            13: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                    ],
                                    "label": "Відповідь",
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 12), ("answer", 13)]],
                                {"label": "Питання"},
                            ),
                            15: (
                                "wagtail.blocks.ListBlock",
                                (14,),
                                {"label": "Питання й відповіді", "min_num": 1},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 11), ("items", 15)]],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Обов'язково: назва допомагає користувачам скрінрідерів зрозуміти таблицю.",
                                    "label": "Назва таблиці",
                                    "max_length": 200,
                                },
                            ),
                            18: ("wagtail.blocks.CharBlock", (), {"label": "Текст"}),
                            19: ("wagtail.blocks.DecimalBlock", (), {"label": "Число"}),
                            20: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "link"],
                                    "label": "Текст із посиланнями",
                                },
                            ),
                            21: (
                                "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                                [[("text", 18), ("number", 19), ("rich_text", 20)]],
                                {"label": "Таблиця"},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("caption", 17), ("table", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Інформація"),
                                        ("success", "Успіх / підтвердження"),
                                        ("warning", "Увага"),
                                        ("danger", "Важливе попередження"),
                                    ],
                                    "label": "Тип",
                                },
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Заголовок",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            25: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [[("variant", 23), ("title", 24), ("text", 25)]],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Назва (відділ, посада)", "max_length": 150},
                            ),
                            28: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Адреса",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Кабінет",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            30: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Як показувати, напр. (05361) 7-00-00",
                                    "label": "Телефон",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            31: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {"label": "Електронна пошта", "required": False},
                            ),
                            32: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Години прийому",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            33: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 27),
                                        ("address", 28),
                                        ("room", 29),
                                        ("phone", 30),
                                        ("email", 31),
                                        ("hours", 32),
                                    ]
                                ],
                                {},
                            ),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Текст кнопки", "max_length": 60},
                            ),
                            35: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Сторінка сайту", "required": False},
                            ),
                            36: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Або зовнішнє посилання", "required": False},
                            ),
                            37: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Основна кнопка"),
                                        ("secondary", "Другорядна кнопка"),
                                    ],
                                    "label": "Вигляд",
                                },
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 34),
                                        ("page", 35),
                                        ("url", 36),
                                        ("style", 37),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Необов'язково: показується під картками підрозділів (наприклад, часті питання).",
                        verbose_name="Додатковий вміст",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розділ (лендинг)",
                "verbose_name_plural": "Розділи (лендинги)",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="1–2 речення під заголовком: для кого сторінка і що тут можна дізнатися.",
                        max_length=400,
                        verbose_name="Вступ",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 3),
                            ("image", 6),
                            ("documents", 10),
                            ("accordion", 16),
                            ("table", 22),
                            ("callout", 26),
                            ("contact_card", 33),
                            ("button", 38),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Текст заголовка", "max_length": 120},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Заголовок розділу (H2)"),
                                        ("h3", "Підзаголовок (H3)"),
                                    ],
                                    "help_text": "H3 використовуйте лише всередині розділу з H2, щоб не порушувати структуру.",
                                    "label": "Рівень",
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("apps.core.blocks.ParagraphBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {
                                    "help_text": "Альтернативний текст обов'язковий: опишіть, що зображено і навіщо це на сторінці. Позначте як декоративне, лише якщо зображення не несе змісту.",
                                    "label": "Зображення",
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Підпис",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Заголовок списку",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Документ"},
                            ),
                            9: (
                                "wagtail.blocks.ListBlock",
                                (8,),
                                {"label": "Документи", "min_num": 1},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 7), ("documents", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Наприклад, «Часті питання».",
                                    "label": "Заголовок блоку",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Питання", "max_length": 250},
                            ),
                            13: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                    ],
                                    "label": "Відповідь",
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 12), ("answer", 13)]],
                                {"label": "Питання"},
                            ),
                            15: (
                                "wagtail.blocks.ListBlock",
                                (14,),
                                {"label": "Питання й відповіді", "min_num": 1},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 11), ("items", 15)]],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Обов'язково: назва допомагає користувачам скрінрідерів зрозуміти таблицю.",
                                    "label": "Назва таблиці",
                                    "max_length": 200,
                                },
                            ),
                            18: ("wagtail.blocks.CharBlock", (), {"label": "Текст"}),
                            19: ("wagtail.blocks.DecimalBlock", (), {"label": "Число"}),
                            20: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "link"],
                                    "label": "Текст із посиланнями",
                                },
                            ),
                            21: (
                                "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                                [[("text", 18), ("number", 19), ("rich_text", 20)]],
                                {"label": "Таблиця"},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("caption", 17), ("table", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Інформація"),
                                        ("success", "Успіх / підтвердження"),
                                        ("warning", "Увага"),
                                        ("danger", "Важливе попередження"),
                                    ],
                                    "label": "Тип",
                                },
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Заголовок",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            25: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [[("variant", 23), ("title", 24), ("text", 25)]],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Назва (відділ, посада)", "max_length": 150},
                            ),
                            28: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Адреса",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Кабінет",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            30: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Як показувати, напр. (05361) 7-00-00",
                                    "label": "Телефон",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            31: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {"label": "Електронна пошта", "required": False},
                            ),
                            32: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Години прийому",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            33: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 27),
                                        ("address", 28),
                                        ("room", 29),
                                        ("phone", 30),
                                        ("email", 31),
                                        ("hours", 32),
                                    ]
                                ],
                                {},
                            ),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Текст кнопки", "max_length": 60},
                            ),
                            35: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Сторінка сайту", "required": False},
                            ),
                            36: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Або зовнішнє посилання", "required": False},
                            ),
                            37: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Основна кнопка"),
                                        ("secondary", "Другорядна кнопка"),
                                    ],
                                    "label": "Вигляд",
                                },
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 34),
                                        ("page", 35),
                                        ("url", 36),
                                        ("style", 37),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Вміст",
                    ),
                ),
                (
                    "show_toc",
                    models.BooleanField(
                        default=True,
                        help_text="Зміст зі посиланнями на заголовки H2; з'являється, якщо їх щонайменше 3.",
                        verbose_name="Показувати «На цій сторінці»",
                    ),
                ),
            ],
            options={
                "verbose_name": "Текстова сторінка",
                "verbose_name_plural": "Текстові сторінки",
            },
            bases=("wagtailcore.page",),
        ),
    ]
